### ISSUE TITLE
Submit ticket organization pages

### ISSUE THREAD

**Issue by ethanrose** [ethanrose/ticketz-io#10]
Every organization should get their own "organization" page, for example:
http://ticketz.io/my-organization
http://ticketz.io/someone-elses-organization

 where their users can go to submit new tickets. every organization will set their own "submittal" password to prevent random people from being able to submit a ticket

This feature is not yet implemented

**Comment by Josh5231** [comment]
Do you intend for the user to login and then be redirected/routed to this page or is it meant to be there starting page?

**Comment by ethanrose** [comment]
Meant to be their starting page, so the end users don't actually need to "log in".
When the owner fills out the "sign up" form and their organizational account is made, they will get a unique URL to share with their organization. (They could put it on their organization website with the submittal password so that their own end users can submit tickets)

only the IT staff & organization owner will be users

**Comment by ethanrose** [comment]
Does that make sense to do it that way? On the one hand there's the security issue since it's public for anyone to react the organization page, but on the other hand, I know the IT departments wouldn't want to manage creating/deleting thousands of user accounts.

**Comment by Josh5231** [comment]
I think that having it where the user signs up and supplies the organization password set by the admin may be the best coarse. So that the only way to get to the organizations page is to be logged in with an account associated with the organization. Then admin would only need to maintain / remove user when needed.

**Comment by ethanrose** [comment]
Agreed, that makes sense. So the user would need to supply the organization password and something else to make sure that they get attached to the correct organization then

**Comment by Josh5231** [comment]
Yeah, this would also make it a little easier for the end user.  As they would not have to remember/store and supply the organization's password everytime they needed to submit a ticket. It would just be associated with their account.

**Comment by ethanrose** [comment]
Right, and then their name and email address as well, and other basic info, then it would be really easy for them to submit a ticket. I'm thinking I want to switch to using emails instead of usernames. Everything can be based on the @myorganization.com extension of the emails.. so a user creates an account--

email: me@myorg.com
organization password: ******
(server checks the myorg.com organization, and sees if the password matches that organization)
if true --> creates account
if not --> invalid password error

**Comment by Josh5231** [comment]
Sounds good. You will need to supply a bit more info if you want help implementing this. Such as the layout for the mongoose schema for the users and the organizations. Also a detailed flow chart would be very helpful.

**Comment by Josh5231** [comment]
Sorry I meant any changes to the schemas.

**Comment by ethanrose** [comment]
Okay, I will work on that!

**Comment by ethanrose** [comment]
Actually I had an idea, instead of organization pages, or user accounts. just a "+ New Ticket" button on the home page, where a user can click to open a simple form. Their work email address that they use @thiscompany.com will find the organization, and they will still use the "submittal password", that is set up by each organization. That keeps it really simple though for us and more importantly for the end users.. they just have to click a button on the home page and put in the info.
