### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by Josh5231** [ethanrose/ticketz-io#3]
The Mongo db uri and the session secret should be set as environmental variables. Right now both are exposed in the server.js file.

**Comment by ethanrose** [comment]
Thanks! I was wondering what the normal procedure is -- How do other people connect to them if they are set as env variables? Do they remain env variables if someone forks/clones it?

**Comment by Josh5231** [comment]
Well the environmental variables are supplied by the host at runtime. So when they run your app on your host they will connect to your db. If they fork or clone then they will have to setup there own db and secret if they want to host it on their own site. However if they are just contributing to this project and want to test it, it easy enough to setup a local db and feed in those variables. ( PS I am no expert when it comes to these things, so please make sure to do own research. )

**Comment by ethanrose** [comment]
Ah, so generally each person has their own DB instead of sharing.. that makes sense!

**Comment by Josh5231** [comment]
Yeah basically. But the big concern is that mlab and most mongo db servers use the same uri schema that includes your user name and password. So right now I could easily write an app that could access your db and do whatever I wanted to the data stored there.

**Comment by ethanrose** [comment]
I've got it now, and whenever webstorm finally stops doing its annoying indexing I will push the change here haha! :)

**Comment by ethanrose** [comment]
Got it, env variable for mongodb is set, and I included comments at the top of server.js explaining how to set it on your local machine as well!
